package io.imking.core.mapper;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.DELETE_FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.FROM;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.ORDER_BY;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT;
import static org.apache.ibatis.jdbc.SqlBuilder.SELECT_DISTINCT;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import io.imking.core.domain.User;
import io.imking.core.domain.UserExample.Criteria;
import io.imking.core.domain.UserExample.Criterion;
import io.imking.core.domain.UserExample;
import java.util.List;
import java.util.Map;

public class UserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_user
     *
     * @mbggenerated
     */
    public String countByExample(UserExample example) {
        BEGIN();
        SELECT("count(*)");
        FROM("kd_user");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_user
     *
     * @mbggenerated
     */
    public String deleteByExample(UserExample example) {
        BEGIN();
        DELETE_FROM("kd_user");
        applyWhere(example, false);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_user
     *
     * @mbggenerated
     */
    public String insertSelective(User record) {
        BEGIN();
        INSERT_INTO("kd_user");
        
        if (record.getId() != null) {
            VALUES("id", "#{id,jdbcType=BIGINT}");
        }
        
        if (record.getUserName() != null) {
            VALUES("userName", "#{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getPwd() != null) {
            VALUES("pwd", "#{pwd,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            VALUES("email", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getSlat() != null) {
            VALUES("slat", "#{slat,jdbcType=VARCHAR}");
        }
        
        if (record.getAvatar() != null) {
            VALUES("avatar", "#{avatar,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            VALUES("sex", "#{sex,jdbcType=TINYINT}");
        }
        
        if (record.getPhone() != null) {
            VALUES("phone", "#{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getBrithday() != null) {
            VALUES("brithday", "#{brithday,jdbcType=VARCHAR}");
        }
        
        if (record.getNickName() != null) {
            VALUES("nickName", "#{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getTrueName() != null) {
            VALUES("trueName", "#{trueName,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            VALUES("status", "#{status,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            VALUES("createTime", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            VALUES("updateTime", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAddress() != null) {
            VALUES("address", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkyears() != null) {
            VALUES("workyears", "#{workyears,jdbcType=INTEGER}");
        }
        
        if (record.getJob() != null) {
            VALUES("job", "#{job,jdbcType=VARCHAR}");
        }
        
        if (record.getDream() != null) {
            VALUES("dream", "#{dream,jdbcType=VARCHAR}");
        }
        
        if (record.getIntroduce() != null) {
            VALUES("introduce", "#{introduce,jdbcType=VARCHAR}");
        }
        
        if (record.getBalance() != null) {
            VALUES("balance", "#{balance,jdbcType=BIGINT}");
        }
        
        if (record.getPoints() != null) {
            VALUES("points", "#{points,jdbcType=BIGINT}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_user
     *
     * @mbggenerated
     */
    public String selectByExample(UserExample example) {
        BEGIN();
        if (example != null && example.isDistinct()) {
            SELECT_DISTINCT("id");
        } else {
            SELECT("id");
        }
        SELECT("userName");
        SELECT("pwd");
        SELECT("email");
        SELECT("slat");
        SELECT("avatar");
        SELECT("sex");
        SELECT("phone");
        SELECT("brithday");
        SELECT("nickName");
        SELECT("trueName");
        SELECT("status");
        SELECT("createTime");
        SELECT("updateTime");
        SELECT("address");
        SELECT("workyears");
        SELECT("job");
        SELECT("dream");
        SELECT("introduce");
        SELECT("balance");
        SELECT("points");
        FROM("kd_user");
        applyWhere(example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            ORDER_BY(example.getOrderByClause());
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_user
     *
     * @mbggenerated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        User record = (User) parameter.get("record");
        UserExample example = (UserExample) parameter.get("example");
        
        BEGIN();
        UPDATE("kd_user");
        
        if (record.getId() != null) {
            SET("id = #{record.id,jdbcType=BIGINT}");
        }
        
        if (record.getUserName() != null) {
            SET("userName = #{record.userName,jdbcType=VARCHAR}");
        }
        
        if (record.getPwd() != null) {
            SET("pwd = #{record.pwd,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{record.email,jdbcType=VARCHAR}");
        }
        
        if (record.getSlat() != null) {
            SET("slat = #{record.slat,jdbcType=VARCHAR}");
        }
        
        if (record.getAvatar() != null) {
            SET("avatar = #{record.avatar,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            SET("sex = #{record.sex,jdbcType=TINYINT}");
        }
        
        if (record.getPhone() != null) {
            SET("phone = #{record.phone,jdbcType=VARCHAR}");
        }
        
        if (record.getBrithday() != null) {
            SET("brithday = #{record.brithday,jdbcType=VARCHAR}");
        }
        
        if (record.getNickName() != null) {
            SET("nickName = #{record.nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getTrueName() != null) {
            SET("trueName = #{record.trueName,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{record.status,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("updateTime = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAddress() != null) {
            SET("address = #{record.address,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkyears() != null) {
            SET("workyears = #{record.workyears,jdbcType=INTEGER}");
        }
        
        if (record.getJob() != null) {
            SET("job = #{record.job,jdbcType=VARCHAR}");
        }
        
        if (record.getDream() != null) {
            SET("dream = #{record.dream,jdbcType=VARCHAR}");
        }
        
        if (record.getIntroduce() != null) {
            SET("introduce = #{record.introduce,jdbcType=VARCHAR}");
        }
        
        if (record.getBalance() != null) {
            SET("balance = #{record.balance,jdbcType=BIGINT}");
        }
        
        if (record.getPoints() != null) {
            SET("points = #{record.points,jdbcType=BIGINT}");
        }
        
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_user
     *
     * @mbggenerated
     */
    public String updateByExample(Map<String, Object> parameter) {
        BEGIN();
        UPDATE("kd_user");
        
        SET("id = #{record.id,jdbcType=BIGINT}");
        SET("userName = #{record.userName,jdbcType=VARCHAR}");
        SET("pwd = #{record.pwd,jdbcType=VARCHAR}");
        SET("email = #{record.email,jdbcType=VARCHAR}");
        SET("slat = #{record.slat,jdbcType=VARCHAR}");
        SET("avatar = #{record.avatar,jdbcType=VARCHAR}");
        SET("sex = #{record.sex,jdbcType=TINYINT}");
        SET("phone = #{record.phone,jdbcType=VARCHAR}");
        SET("brithday = #{record.brithday,jdbcType=VARCHAR}");
        SET("nickName = #{record.nickName,jdbcType=VARCHAR}");
        SET("trueName = #{record.trueName,jdbcType=VARCHAR}");
        SET("status = #{record.status,jdbcType=TINYINT}");
        SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        SET("updateTime = #{record.updateTime,jdbcType=TIMESTAMP}");
        SET("address = #{record.address,jdbcType=VARCHAR}");
        SET("workyears = #{record.workyears,jdbcType=INTEGER}");
        SET("job = #{record.job,jdbcType=VARCHAR}");
        SET("dream = #{record.dream,jdbcType=VARCHAR}");
        SET("introduce = #{record.introduce,jdbcType=VARCHAR}");
        SET("balance = #{record.balance,jdbcType=BIGINT}");
        SET("points = #{record.points,jdbcType=BIGINT}");
        
        UserExample example = (UserExample) parameter.get("example");
        applyWhere(example, true);
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_user
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(User record) {
        BEGIN();
        UPDATE("kd_user");
        
        if (record.getUserName() != null) {
            SET("userName = #{userName,jdbcType=VARCHAR}");
        }
        
        if (record.getPwd() != null) {
            SET("pwd = #{pwd,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getSlat() != null) {
            SET("slat = #{slat,jdbcType=VARCHAR}");
        }
        
        if (record.getAvatar() != null) {
            SET("avatar = #{avatar,jdbcType=VARCHAR}");
        }
        
        if (record.getSex() != null) {
            SET("sex = #{sex,jdbcType=TINYINT}");
        }
        
        if (record.getPhone() != null) {
            SET("phone = #{phone,jdbcType=VARCHAR}");
        }
        
        if (record.getBrithday() != null) {
            SET("brithday = #{brithday,jdbcType=VARCHAR}");
        }
        
        if (record.getNickName() != null) {
            SET("nickName = #{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getTrueName() != null) {
            SET("trueName = #{trueName,jdbcType=VARCHAR}");
        }
        
        if (record.getStatus() != null) {
            SET("status = #{status,jdbcType=TINYINT}");
        }
        
        if (record.getCreateTime() != null) {
            SET("createTime = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            SET("updateTime = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getAddress() != null) {
            SET("address = #{address,jdbcType=VARCHAR}");
        }
        
        if (record.getWorkyears() != null) {
            SET("workyears = #{workyears,jdbcType=INTEGER}");
        }
        
        if (record.getJob() != null) {
            SET("job = #{job,jdbcType=VARCHAR}");
        }
        
        if (record.getDream() != null) {
            SET("dream = #{dream,jdbcType=VARCHAR}");
        }
        
        if (record.getIntroduce() != null) {
            SET("introduce = #{introduce,jdbcType=VARCHAR}");
        }
        
        if (record.getBalance() != null) {
            SET("balance = #{balance,jdbcType=BIGINT}");
        }
        
        if (record.getPoints() != null) {
            SET("points = #{points,jdbcType=BIGINT}");
        }
        
        WHERE("id = #{id,jdbcType=BIGINT}");
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kd_user
     *
     * @mbggenerated
     */
    protected void applyWhere(UserExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            WHERE(sb.toString());
        }
    }
}