package io.imking.core.domain;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.slat
     *
     * @mbggenerated
     */
    private String slat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.avatar
     *
     * @mbggenerated
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.sex
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.brithday
     *
     * @mbggenerated
     */
    private String brithday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.nickName
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.trueName
     *
     * @mbggenerated
     */
    private String trueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.workyears
     *
     * @mbggenerated
     */
    private Integer workyears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.job
     *
     * @mbggenerated
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.dream
     *
     * @mbggenerated
     */
    private String dream;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.introduce
     *
     * @mbggenerated
     */
    private String introduce;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.balance
     *
     * @mbggenerated
     */
    private Long balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kd_user.points
     *
     * @mbggenerated
     */
    private Long points;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.id
     *
     * @return the value of kd_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.id
     *
     * @param id the value for kd_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.userName
     *
     * @return the value of kd_user.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.userName
     *
     * @param userName the value for kd_user.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.pwd
     *
     * @return the value of kd_user.pwd
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.pwd
     *
     * @param pwd the value for kd_user.pwd
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.email
     *
     * @return the value of kd_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.email
     *
     * @param email the value for kd_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.slat
     *
     * @return the value of kd_user.slat
     *
     * @mbggenerated
     */
    public String getSlat() {
        return slat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.slat
     *
     * @param slat the value for kd_user.slat
     *
     * @mbggenerated
     */
    public void setSlat(String slat) {
        this.slat = slat == null ? null : slat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.avatar
     *
     * @return the value of kd_user.avatar
     *
     * @mbggenerated
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.avatar
     *
     * @param avatar the value for kd_user.avatar
     *
     * @mbggenerated
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.sex
     *
     * @return the value of kd_user.sex
     *
     * @mbggenerated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.sex
     *
     * @param sex the value for kd_user.sex
     *
     * @mbggenerated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.phone
     *
     * @return the value of kd_user.phone
     *
     * @mbggenerated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.phone
     *
     * @param phone the value for kd_user.phone
     *
     * @mbggenerated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.brithday
     *
     * @return the value of kd_user.brithday
     *
     * @mbggenerated
     */
    public String getBrithday() {
        return brithday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.brithday
     *
     * @param brithday the value for kd_user.brithday
     *
     * @mbggenerated
     */
    public void setBrithday(String brithday) {
        this.brithday = brithday == null ? null : brithday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.nickName
     *
     * @return the value of kd_user.nickName
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.nickName
     *
     * @param nickName the value for kd_user.nickName
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.trueName
     *
     * @return the value of kd_user.trueName
     *
     * @mbggenerated
     */
    public String getTrueName() {
        return trueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.trueName
     *
     * @param trueName the value for kd_user.trueName
     *
     * @mbggenerated
     */
    public void setTrueName(String trueName) {
        this.trueName = trueName == null ? null : trueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.status
     *
     * @return the value of kd_user.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.status
     *
     * @param status the value for kd_user.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.createTime
     *
     * @return the value of kd_user.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.createTime
     *
     * @param createTime the value for kd_user.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.updateTime
     *
     * @return the value of kd_user.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.updateTime
     *
     * @param updateTime the value for kd_user.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.address
     *
     * @return the value of kd_user.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.address
     *
     * @param address the value for kd_user.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.workyears
     *
     * @return the value of kd_user.workyears
     *
     * @mbggenerated
     */
    public Integer getWorkyears() {
        return workyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.workyears
     *
     * @param workyears the value for kd_user.workyears
     *
     * @mbggenerated
     */
    public void setWorkyears(Integer workyears) {
        this.workyears = workyears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.job
     *
     * @return the value of kd_user.job
     *
     * @mbggenerated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.job
     *
     * @param job the value for kd_user.job
     *
     * @mbggenerated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.dream
     *
     * @return the value of kd_user.dream
     *
     * @mbggenerated
     */
    public String getDream() {
        return dream;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.dream
     *
     * @param dream the value for kd_user.dream
     *
     * @mbggenerated
     */
    public void setDream(String dream) {
        this.dream = dream == null ? null : dream.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.introduce
     *
     * @return the value of kd_user.introduce
     *
     * @mbggenerated
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.introduce
     *
     * @param introduce the value for kd_user.introduce
     *
     * @mbggenerated
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce == null ? null : introduce.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.balance
     *
     * @return the value of kd_user.balance
     *
     * @mbggenerated
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.balance
     *
     * @param balance the value for kd_user.balance
     *
     * @mbggenerated
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kd_user.points
     *
     * @return the value of kd_user.points
     *
     * @mbggenerated
     */
    public Long getPoints() {
        return points;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kd_user.points
     *
     * @param points the value for kd_user.points
     *
     * @mbggenerated
     */
    public void setPoints(Long points) {
        this.points = points;
    }
}